// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by manual edit of ffigen bindings.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for `src/kokoro_tts.h`.
class KokoroTtsBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  KokoroTtsBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  KokoroTtsBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int kokoro_init(
    ffi.Pointer<ffi.Char> model_path,
    ffi.Pointer<ffi.Char> voices_path,
    ffi.Pointer<ffi.Char> espeak_data_path,
  ) {
    return _kokoro_init(
      model_path,
      voices_path,
      espeak_data_path,
    );
  }

  late final _kokoro_initPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('kokoro_init');
  late final _kokoro_init = _kokoro_initPtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  int kokoro_is_initialized() {
    return _kokoro_is_initialized();
  }

  late final _kokoro_is_initializedPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('kokoro_is_initialized');
  late final _kokoro_is_initialized =
      _kokoro_is_initializedPtr.asFunction<int Function()>();

  int kokoro_synthesize(
    ffi.Pointer<ffi.Char> text,
    ffi.Pointer<ffi.Char> voice_name,
    ffi.Pointer<ffi.Char> output_wav_path,
    double speed,
  ) {
    return _kokoro_synthesize(
      text,
      voice_name,
      output_wav_path,
      speed,
    );
  }

  late final _kokoro_synthesizePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Float)>>('kokoro_synthesize');
  late final _kokoro_synthesize = _kokoro_synthesizePtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, double)>();

  void kokoro_free() {
    return _kokoro_free();
  }

  late final _kokoro_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('kokoro_free');
  late final _kokoro_free = _kokoro_freePtr.asFunction<void Function()>();
}
